### ISSUE TITLE
Zed Logs

### ISSUE THREAD

**Issue by xcrap** [evrsen/zed-log#2]
I've installed this extension and works fine with log files but for example opening any kind of Logs from Zed it makes absolutely nothing., it would be cool to add support for Zed Logs as well.

**Comment by ghost** [comment]
Hi, thanks for reaching out! I'm not sure if this is currently possible, the zed logs doesn't seem to use the ``.log`` extension and if my understanding is right the current version of extensions cannot match agains path prefixes (I could be wrong, but I haven't found anything in the authoring section of the extensions repository). Maybe we need to PR to Zed adding the ``.log`` suffix to its logs?

**Comment by xcrap** [comment]
Oh I see. Well I understand it's just a bit awkward not to see their own log errors formatted. 
Yeah suggesting adding .log or they have some sort of mechanism to warn that those files should be treated as log files would be nice, but thanks for the clarification :)
